name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version: ["27.2", "28.2", "29.4", "30.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Emacs ${{ matrix.emacs_version }}
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Install Eldev
        run: |
          mkdir -p "$HOME/.local/bin"
          curl -fsSL https://raw.githubusercontent.com/emacs-eldev/eldev/master/bin/eldev > "$HOME/.local/bin/eldev"
          chmod +x "$HOME/.local/bin/eldev"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Run tests (ERT via Eldev)
        run: eldev -dtT test

